//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybozu.CrossSync {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cybozu.CrossSync.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cybozu Account 1: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account1Error {
            get {
                return ResourceManager.GetString("Account1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cybozu Account 2: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account2Error {
            get {
                return ResourceManager.GetString("Account2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This event is created by Cybozu CrossSync. (Don&apos;t remove ths line.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CrossSyncDescription {
            get {
                return ResourceManager.GetString("CrossSyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The trial period, or the expiration date of the service license of Cybozu Garoon has expired.
        ///
        ///Cybozu CrossSync uses Cybozu Garoon API. Depending on the version of the prorudct, you have to purchase the service license of the product for API use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GaroonLicenseExpires {
            get {
                return ResourceManager.GetString("GaroonLicenseExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Not synchronized) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSynchronized {
            get {
                return ResourceManager.GetString("NotSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The trial period, or the expiration date of the maintenance license of Cybozu Office has expired.
        ///
        ///Cybozu CrossSync uses Cybozu Office API. Depending on the version of the prorudct, you have to purchase the maintenance license of the product for API use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OfficeLicenseExpires {
            get {
                return ResourceManager.GetString("OfficeLicenseExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postfix is necessary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PostfixIsNecessary {
            get {
                return ResourceManager.GetString("PostfixIsNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cybozu CrossSync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
    }
}
